package com.java.Exception;

public class ExceptionPropagation {

	public static void main(String[] args) {
		System.out.println("main start");
		System.out.println("main end");
	}
	static void staticFun1() {
		System.out.println("staticFun1 start");
		try {
			staticFun2();
		} catch (Exception e) {
			System.out.println("exception handled using ExceptionPropagation");// TODO: handle exception
		}
		System.out.println("staticFun1 end");
	}
	static void staticFun2() {
		System.out.println("staticFun2 start");
		int a=10/0;//Exception
		System.out.println("staticFun2 end");
	}
}
